//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientMembers = new HashSet<ClientMember>();
        }
    
        public long clientID { get; set; }
        public string name { get; set; }
        public string fatherName { get; set; }
        public string nationalCode { get; set; }
        public string jobtitle { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public string homeAdress { get; set; }
        public Nullable<byte> healthStateID { get; set; }
        public string mobile { get; set; }
        public Nullable<long> mosqueID { get; set; }
        public Nullable<byte> pirorityID { get; set; }
        public string need { get; set; }
        public Nullable<bool> maried { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<short> educationID { get; set; }
        public Nullable<bool> sex { get; set; }
        public Nullable<byte> homeStateID { get; set; }
        public string homeStateDescription { get; set; }
        public string phone { get; set; }
        public Nullable<bool> Continus { get; set; }
        public Nullable<bool> goneShrine { get; set; }
        public string moneySource { get; set; }
        public Nullable<bool> benefit { get; set; }
        public Nullable<byte> benfitTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMember> ClientMembers { get; set; }
        public virtual HealthState HealthState { get; set; }
        public virtual Mosque Mosque { get; set; }
        public virtual Piority Piority { get; set; }
        public virtual User User { get; set; }
        public virtual HomeState HomeState { get; set; }
        public virtual Education Education { get; set; }
    }
}
