//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientMembers = new HashSet<ClientMember>();
        }
    
        public long clientID { get; set; }
        public string name { get; set; }
        public string fatherName { get; set; }
        public string nationalCode { get; set; }
        public string jobtitle { get; set; }
        public Nullable<System.DateTime> birthDay { get; set; }
        public string homeAdress { get; set; }
        public Nullable<byte> healthStateID { get; set; }
        public string mobile { get; set; }
        public Nullable<long> mosqueID { get; set; }
        public Nullable<byte> pirorityID { get; set; }
        public string need { get; set; }
        public Nullable<bool> maried { get; set; }
        public Nullable<long> userID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientMember> ClientMembers { get; set; }
        public virtual HealthState HealthState { get; set; }
        public virtual Mosque Mosque { get; set; }
        public virtual Piority Piority { get; set; }
        public virtual User User { get; set; }
    }
}
