//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faq
    {
        public int faqID { get; set; }
        public string question { get; set; }
        public Nullable<long> userID { get; set; }
    
        public virtual User User { get; set; }
    }
}
