//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AstanEntities : DbContext
    {
        public AstanEntities()
            : base("name=AstanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientMember> ClientMembers { get; set; }
        public virtual DbSet<HealthState> HealthStates { get; set; }
        public virtual DbSet<Mosque> Mosques { get; set; }
        public virtual DbSet<Piority> Piorities { get; set; }
        public virtual DbSet<userGroup> userGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<BenefitType> BenefitTypes { get; set; }
        public virtual DbSet<HomeState> HomeStates { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
    }
}
