//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mosque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mosque()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public long mosqueID { get; set; }
        public string mosqueName { get; set; }
        public string adress { get; set; }
        public string bossName { get; set; }
        public string phone { get; set; }
        public string bossMobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
